### ISSUE TITLE
Inconsistend showNotification behaviour at NotificationInterop

### ISSUE THREAD

**Issue by NLLAPPS** [Karn/notify#57]
I have come across an issue where I was unable to cancel stacked notifications. I have traced it to showNotification at NotificationInterop

Library alters the expected functionality without clear indication.

`fun showNotification(notificationManager: NotificationManager, id: Int?, notification: NotificationCompat.Builder): Int {
        val key = NotifyExtender.getKey(notification.extras)
        var id = id ?: Utils.getRandomInt()

        if (key != null) {
            id = key.hashCode()
            notificationManager.notify(key.toString(), id, notification.build())
        } else {
            notificationManager.notify(id, notification.build())
        }

        return id
    }
`

I expected "id" I have provided to e used when showing notification but since my notification was stackable, library used  id = key.hashCode() as id and key.toString() as tag and this prevented me cancelling with.

It looks complicated and I have no advise on what should this be handled. I have simply added notes to my notification function to remind this issue to myself in the future

**Comment by Karn** [comment]
Hey @NLLAPPS,

Thanks for submitting this, you'll notice that the documentation states that this field will be ignored if the notification is a stackable type. Unfortunately, this is bad API design on my part because it ignores the notification id that is provided. However, the function returns an integer which corresponds to the ID that was used to create the notification which you can use.

In the near future, this will be replaced to return an ID on your behalf.

**Comment by P1NG2WIN** [comment]
is it fixed?
